name: Deploy Docker Image to Server

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Deploy to Linux server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/score_headlines_app_personal:latest

            # Stop and remove any existing container
            docker stop score_headlines_app_personal || true
            docker rm score_headlines_app_personal || true

            # Run the updated image, this is a test commit, second test, third test check
            docker run -d \
              --name score_headlines_app_personal \
              -p 8081:8081 \
              -p 9081:9081 \
              -v /opt/assignment_outputs:/app/results \
              ${{ secrets.DOCKER_USERNAME }}/score_headlines_app_personal:latest
