name: Python Checks

on:
  push:
    branches: [main, prod]
  pull_request:
    branches: [main, prod]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements_fixed.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_fixed.txt
        pip install pylint mypy pytest types-requests

    - name: Run pylint
      run: pylint --rcfile=.pylintrc assignment4/ assignment4/tests/

    - name: Run mypy
      run: mypy assignment4

    - name: Run tests
      run: pytest assignment4/tests
