name: Python Checks

on:
  push:
    branches:
      - main
      - prod
  pull_request:
    branches:
      - main
      - prod

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install -r requirements_fixed.txt
        python -m pip install pylint
        python -m pip install mypy
        python -m pip install pytest
        python -m pip install --upgrade pip


    - name: Run pylint
      run: |
        pylint --rcfile=.pylintrc

    - name: Run mypy on assignment4
      run: |
        mypy assignment4

    - name: Run pytest on assignment4
      run: |
        pytest assignment4/tests
